🐛  fix find pool
interest-protocol/movement pull request #100
Opened 2024-03-23 20:00 UTC by git-marcopitra

2024-03-25 20:19 UTC, KipandaJr commented
![image](https://github.com/interest-protocol/movement/assets/34079870/cdac5538-c659-4c30-bc80-57801067146f)

Can search when form its empty

2024-03-25 20:21 UTC, MarioBatalha approved these changes

2024-03-25 20:22 UTC, KipandaJr commented
![image](https://github.com/interest-protocol/movement/assets/34079870/b9f2a1d3-97ae-4abd-83ce-acc796d15a0f)

need a loading modal

2024-04-02 00:36 UTC, KipandaJr requested changes
solve the conflits plz

2024-04-02 19:40 UTC, merged