:sparkles: Adding useDialog
interest-protocol/movement pull request #22
Opened 2024-02-22 22:45 UTC by KipandaJr

2024-02-22 22:51 UTC, KipandaJr reviewed
Auto review done ✅

2024-02-24 17:20 UTC, MarioBatalha approved these changes

2024-02-25 15:59 UTC, git-marcopitra commented on hooks/use-dialog/use-dialog.types.ts
> +import { DialogProps } from '@interest-protocol/ui-kit/dist/components/dialog/dialog.types';
Is it correct? I think no, we are not export `dist` folder

2024-02-25 16:03 UTC, git-marcopitra requested changes
![image](https://github.com/interest-protocol/movement/assets/59171412/25b70294-9067-4d3e-98c9-0ae772e99e64)
Pushing branches with build bug

2024-02-25 16:17 UTC, git-marcopitra approved these changes

2024-02-25 16:20 UTC, merged