:sparkles: feat: pool search params
interest-protocol/movement pull request #255
Opened 2024-09-26 13:42 UTC by atilasousa

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208395299081552

2024-09-26 18:58 UTC, KipandaJr approved these changes

2024-09-26 19:06 UTC, MarioBatalha requested changes

2024-09-26 19:06 UTC, MarioBatalha commented on views/pools/pool-filter/dropdown/index.tsx
> +      console.log('newQuery', newQuery);
Remove the console.log

2024-09-30 19:09 UTC, MarioBatalha approved these changes

2024-09-30 19:17 UTC, merged