:sparkles: Pool Details Header
interest-protocol/movement pull request #26
Opened 2024-02-26 22:06 UTC by KipandaJr

2024-02-26 22:57 UTC, git-marcopitra requested changes

2024-02-26 22:57 UTC, git-marcopitra commented on views/pool-details/index.tsx
> +            acc === '' ? token.symbol : acc + '•' + token.symbol,
Instead `+` concat u must use template string

2024-02-26 22:57 UTC, git-marcopitra commented on views/pools/pool-card/index.tsx
> +      <PoolCardInfo apr="333.45" coins={tokens} />
add this apr to a constant and reuse it inside

2024-02-26 23:18 UTC, git-marcopitra approved these changes

2024-02-26 23:18 UTC, git-marcopitra commented on constants/pools.ts
> +      apr: '3333.45',
remove it from here, cuz apr is a calculated value

2024-02-26 23:18 UTC, git-marcopitra commented on views/pool-details/index.tsx
> +            acc === '' ? token.symbol : `${acc} • ${token.symbol}`,
Simplify to:

```ts
`${acc ? `${acc} • ` :  ''}${token.symbol}`
```

2024-02-26 23:18 UTC, git-marcopitra commented on views/pools/pool-card/index.tsx
`apr` should be a constant here to be calculated later on fetch the values

2024-02-26 23:18 UTC, git-marcopitra commented on views/pools/pool-card/pool-card.types.ts
> +  apr: string;
u can remove it from here

2024-02-27 17:14 UTC, MarioBatalha approved these changes

2024-02-28 20:12 UTC, atilasousa approved these changes

2024-02-28 20:17 UTC, merged