:sparkles: feat: pool header
interest-protocol/movement pull request #28
Opened 2024-02-29 10:44 UTC by atilasousa

2024-02-29 12:01 UTC, MarioBatalha requested changes

2024-02-29 12:01 UTC, MarioBatalha commented on views/pools/header/action-group.tsx
> +          color="black"
use value from theme.

2024-02-29 12:01 UTC, MarioBatalha commented on views/pools/header/search-mobile.tsx
> +        color="black"
Here too

2024-02-29 20:02 UTC, git-marcopitra approved these changes

2024-02-29 20:16 UTC, KipandaJr requested changes

2024-02-29 20:16 UTC, KipandaJr commented on views/pools/index.tsx
> +    <Layout title="">
u can remove this props `title`

2024-02-29 20:16 UTC, KipandaJr commented on views/pools/index.tsx
> +        <Box py="1.5rem">
check this too

2024-02-29 20:20 UTC, KipandaJr approved these changes

2024-03-01 18:08 UTC, MarioBatalha approved these changes

2024-03-01 20:08 UTC, merged