Refactor/pool card
interest-protocol/movement pull request #33
Opened 2024-03-02 00:57 UTC by atilasousa

2024-03-02 18:03 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/movement/assets/34079870/036c2195-545c-4a19-b2c2-2ab948ac3cd5)
 
the page break on this point `1292px`

2024-03-02 18:03 UTC, KipandaJr commented on views/pools/pool-card/index.tsx
> +          borderColor: '#76767A',
Check this color on `ui-kit`

2024-03-02 18:03 UTC, KipandaJr commented on views/pools/pool-card/pool-card-header.tsx
>            >
this tags r not a link on info value like `Volatile` the link has only on Dex name

2024-03-03 22:05 UTC, atilasousa commented on views/pools/pool-card/index.tsx
> +          borderColor: '#76767A',
dosen't exist in colors

2024-03-04 03:07 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/movement/assets/34079870/9de6a3f6-60ec-4d40-a2ce-9a7140ba8867)
not solved the responsiviness

2024-03-05 19:48 UTC, MarioBatalha requested changes

2024-03-05 19:48 UTC, MarioBatalha commented on views/pools/pool-card/pool-card-header.tsx
> +          gap="0"
This gap and padding are unnecessary

2024-03-05 19:48 UTC, MarioBatalha commented on views/pools/pool-card/pool-card-header.tsx
> +          px="0"
Are u sure that this px and py is necessary?

2024-03-05 19:48 UTC, MarioBatalha commented on views/pools/pool-card/pool-card-header.tsx
> +      opacity="0"
You could add here some transition effect

2024-03-05 20:48 UTC, KipandaJr approved these changes

2024-03-05 21:03 UTC, MarioBatalha approved these changes

2024-03-05 21:04 UTC, git-marcopitra approved these changes

2024-03-05 21:05 UTC, merged