:sparkles: feat: detail tabs
interest-protocol/movement pull request #35
Opened 2024-03-03 22:02 UTC by atilasousa

2024-03-04 03:15 UTC, KipandaJr requested changes
try use the same effect that we used on tabs, where the focus move slowly between inside tabs
![image](https://github.com/interest-protocol/movement/assets/34079870/2c33b3bf-1b8b-460c-8284-48f7972f5f65)

2024-03-04 03:15 UTC, KipandaJr commented on views/pool-details/index.tsx
> +import PoolDetaislTabs from './pool-details-tabs';
has error in component name

2024-03-04 03:15 UTC, KipandaJr commented on views/pool-details/pool-details-tabs/index.tsx
> +      {items.map((el, index) => (
change `el` to `item`

2024-03-04 03:15 UTC, KipandaJr commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +      borderBottom={isSelected ? '2px solid #0053DB' : ''}
use the `ui-kit` color

2024-03-04 03:15 UTC, KipandaJr commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +  return (
remove return

2024-03-05 19:19 UTC, atilasousa commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +      borderBottom={isSelected ? '2px solid #0053DB' : ''}
it dosen't exist in ui kit

2024-03-05 19:51 UTC, KipandaJr commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +      borderBottom={isSelected ? '2px solid #0053DB' : ''}
![image](https://github.com/interest-protocol/movement/assets/34079870/742c220c-4ade-4277-8a2b-10e845414728)
dont say that dude

2024-03-05 20:51 UTC, KipandaJr approved these changes

2024-03-05 21:08 UTC, git-marcopitra commented
<img width="410" alt="image" src="https://github.com/interest-protocol/movement/assets/59171412/b7ec1cf3-11ad-47b6-86b3-7cfd2c1e7112">
![image](https://github.com/interest-protocol/movement/assets/59171412/e1774c27-1f38-4014-a6ae-b9061d822a60)
<img width="669" alt="image" src="https://github.com/interest-protocol/movement/assets/59171412/3b94f206-917f-4074-8773-976ff83c3880">

2024-03-05 21:10 UTC, git-marcopitra requested changes

2024-03-05 21:10 UTC, git-marcopitra commented on views/pool-details/pool-details-tabs/index.tsx
> +      borderBottom="0.01px solid #C6C6CA"
wrong border

2024-03-05 21:10 UTC, git-marcopitra commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +    <Typography size="small" position="absolute" variant="body">
size `medium`

2024-03-05 21:17 UTC, git-marcopitra requested changes

2024-03-05 21:17 UTC, git-marcopitra commented on views/pool-details/pool-details-tabs/index.tsx
> +      borderBottom="0.01px solid #C6C6CA"
do not use static colors, try to use outline or outlineVariant

2024-03-05 21:17 UTC, git-marcopitra commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +    borderBottom={isSelected ? '2px solid #0053DB' : ''}
Do not use static colors, instead use `primary`

2024-03-05 21:23 UTC, git-marcopitra requested changes

2024-03-05 21:23 UTC, git-marcopitra commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +    borderBottomColor="primary"
isSelected ? 'primary' : 'transparent'

2024-03-05 21:23 UTC, git-marcopitra commented on views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
> +    borderBottom={isSelected ? '2px solid' : ''}
remove the `isSelected` from here

2024-03-05 21:24 UTC, MarioBatalha approved these changes

2024-03-05 21:28 UTC, git-marcopitra approved these changes

2024-03-05 21:28 UTC, merged