:bug: Create details header refactor
interest-protocol/movement pull request #52
Opened 2024-03-08 00:45 UTC by KipandaJr

2024-03-08 09:49 UTC, git-marcopitra requested changes

2024-03-08 09:49 UTC, git-marcopitra commented on views/components/pool-title-bar/index.tsx
>  const PoolTitleBar: FC<PoolTitleBarProps> = ({
That's is not the Way, create a new component for that please

2024-03-08 19:58 UTC, atilasousa approved these changes

2024-03-08 20:07 UTC, MarioBatalha approved these changes

2024-03-09 21:01 UTC, git-marcopitra requested changes

2024-03-09 21:01 UTC, git-marcopitra commented on views/pool-create/header/index.tsx
> +      {name.split('<br />').join('\n')}
BAD APPROACH AGAIN, do something simple, like `{name}`

2024-03-09 21:01 UTC, git-marcopitra commented on views/pool-create/pool-create.data.tsx
> +export const stepTitle: ReadonlyArray<string> = [
`ReadonlyArray<ReactNode>`

2024-03-09 22:23 UTC, git-marcopitra approved these changes

2024-03-09 22:23 UTC, merged