🐛 Fix Swap flow
interest-protocol/movement pull request #66
Opened 2024-03-10 03:25 UTC by git-marcopitra

2024-03-10 18:43 UTC, MarioBatalha approved these changes

2024-03-10 18:56 UTC, MarioBatalha requested changes
<img width="388" alt="Screenshot 2024-03-10 at 19 46 28" src="https://github.com/interest-protocol/movement/assets/37873239/f93a6b79-3cfd-4cac-a870-0da856fa69c6">


Take a look to "swap button" text alignment

2024-03-10 18:56 UTC, MarioBatalha commented on views/swap/swap-preview-button.tsx
> +      bg={isEnabled ? 'filled' : 'outlineContainer'}
<img width="316" alt="Screenshot 2024-03-10 at 19 49 53" src="https://github.com/interest-protocol/movement/assets/37873239/b3f31fc1-22cd-4235-9bd3-be6234a707ac">

Take a look to preview modal button when coins exist

2024-03-11 20:03 UTC, atilasousa approved these changes

2024-03-11 20:39 UTC, KipandaJr approved these changes

2024-03-11 20:40 UTC, merged