:recycle: refactor: pool page
interest-protocol/movement pull request #85
Opened 2024-03-13 20:42 UTC by atilasousa

2024-03-13 21:02 UTC, MarioBatalha requested changes

2024-03-13 21:02 UTC, MarioBatalha commented on views/pools/header/action-group.tsx
> +          fontFamily="Proto"
Change this input to button

2024-03-13 21:02 UTC, MarioBatalha commented on views/pools/header/search-mobile.tsx
>        <TextField
Here too

2024-03-14 19:30 UTC, MarioBatalha requested changes

2024-03-14 19:30 UTC, MarioBatalha commented on views/pools/header/action-group.tsx
> +          bg="#ffffff14"
Use bg  from theme

2024-03-14 19:51 UTC, KipandaJr approved these changes

2024-03-15 19:42 UTC, MarioBatalha approved these changes

2024-03-18 20:19 UTC, git-marcopitra requested changes

2024-03-18 20:19 UTC, git-marcopitra commented on views/pools/pool-filter/index.tsx
> +      display={['grid', 'flex', 'flex', 'flex', 'flex']}
remove the unneeded `flex`

2024-03-18 20:19 UTC, git-marcopitra commented on views/pools/pool-filter/index.tsx
> +        display={['none', 'none', 'inline-flex', 'inline-flex', 'inline-flex']}
remove unneeded `inline-flex`

2024-03-19 13:33 UTC, atilasousa commented on views/pools/pool-filter/index.tsx
> +      display={['grid', 'flex', 'flex', 'flex', 'flex']}
??

2024-03-19 13:33 UTC, atilasousa commented on views/pools/pool-filter/index.tsx
> +        display={['none', 'none', 'inline-flex', 'inline-flex', 'inline-flex']}
unneeded why??

2024-03-26 19:30 UTC, atilasousa commented on views/pools/header/index.tsx
> +      display={'flex'}
why {}?

2024-03-26 19:33 UTC, KipandaJr commented on views/pools/header/index.tsx
> +      display={'flex'}
accident

2024-03-26 20:11 UTC, git-marcopitra approved these changes

2024-03-26 20:12 UTC, merged