:sparkles: find pool doesn't exist
interest-protocol/movement pull request #92
Opened 2024-03-18 21:24 UTC by MarioBatalha

2024-03-18 22:11 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/movement/assets/34079870/1d998f4e-dba7-4a7f-ac78-5b36817ec5c1)
when i add other coin, the other r cleaned...

![image](https://github.com/interest-protocol/movement/assets/34079870/59894002-61d6-47d5-8800-90e1cba37d8f)
this button should be disabled if any field r empty

![image](https://github.com/interest-protocol/movement/assets/34079870/fc93ec8b-76b0-46da-9ea6-338afe5e4f3e)
This modal has a diff BG that other (Find Pool eg.)

![image](https://github.com/interest-protocol/movement/assets/34079870/c6fc2920-c995-4bc9-a97d-901e41efa6e8)
In mobile this modal r not aligned

2024-03-18 22:11 UTC, KipandaJr commented on views/pools/header/index.tsx
> +//import { not } from 'ramda';
remove

2024-03-18 22:11 UTC, KipandaJr commented on views/pools/header/index.tsx
> +  //const handleCloseSearch = () => setShowSearchField(not);
remove

2024-03-19 03:15 UTC, MarioBatalha commented on views/pool-create/select-coins/input/select-token.tsx
> +    });
It's not part of this task.

2024-03-19 03:19 UTC, MarioBatalha commented on constants/fees.ts
Give me a context of your comment

2024-03-20 22:56 UTC, merged